### ISSUE TITLE
mutex.go:239:46: too many errors

### ISSUE THREAD

**Issue by yo1nkers** [ellypaws/stable-diffusion-discord-bot#3]
X:\bots\stable-diffusion-discord-bot> go build
# modernc.org/sqlite/lib
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\defs.go:13:35: undefined: sqlite3_index_constraint
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\defs.go:14:35: undefined: sqlite3_index_orderby
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\defs.go:15:35: undefined: sqlite3_index_constraint_usage
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\mutex.go:19:5: undefined: Xsqlite3_threadsafe
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\mutex.go:29:11: undefined: Xsqlite3_config
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\mutex.go:29:32: undefined: SQLITE_CONFIG_MUTEX
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\mutex.go:29:122: undefined: SQLITE_OK
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\mutex.go:30:8: undefined: Xsqlite3_errstr
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\mutex.go:40:17: undefined: Sqlite3_mutex_methods
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\mutex.go:239:46: undefined: SQLITE_OK
C:\Program Files (x86)\Go\bin\pkg\mod\modernc.org\sqlite@v1.29.1\lib\mutex.go:239:46: too many errors

**Comment by yo1nkers** [comment]
Different issue now.

**Comment by ellypaws** [comment]
Seems like the issue might not be in my end. Feel free to re-open or comment if anything else comes up.

Thanks!

**Comment by yo1nkers** [comment]
> Seems like the issue might not be in my end. Feel free to re-open or comment if anything else comes up.
> 
> Thanks!

You're correct, my apologies. I've tried other forks of this and it appears the issue is concurrent. I will report back if I find a fix.

**Comment by ellypaws** [comment]
For what it's worth, I'm using sqlite@v1.20.1 where it seems you're getting errors from sqlite@v1.29.1 https://github.com/ellypaws/stable-diffusion-discord-bot/blob/cc27d625ec61d51af23cf443a4201495ad4e6490/go.mod#L13

Make sure to run `go mod tidy` before building to fetch the correct libraries according to go.mod
